### ISSUE TITLE
SETUP: Create the Database models

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#10]
- [x] Using ERD, create models in models.py
- [x] import models.py, import user
- [x] add attributes to model
- [x] migrate
- [x] update settings.py with CSRF_TRUSTED_ORIGINA
- [x] Add model to admin.py - import Models
- [x] Test as superuser
- [x] Many deploytment to Heroku
