### ISSUE TITLE
Install Whitenoise

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#14]
- [ ] Install whitenoise
- [ ] Set up settings.py - MIDDLEWARE
- [ ] Run collectstatic
- [ ] Deploy
- [ ] Test 
- [ ] Check python version 
- [ ] Look up supported runtimes and copy closest runtime to the one in my IDE
- [ ] Add python version you copied from the list of support runtimes to the runtime.txt file
