### ISSUE TITLE
USER STORY: View venue details page

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#16]
- [ ] Create a new path in urls.py file
- [ ] In index.html, update the anchor element to point to the post_detail view
- [ ] Add a venue_detail function-based view in views.py
- [ ] Create an images directory in the existing static directory
- [ ] Create a new venue_detail.html file in the templates/venue directory
- [ ] Collect new static files to the static files directory
- [ ] Deploy
- [ ] Test
