### ISSUE TITLE
Build Booking app

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#17]
- [x] Create the app
- [x] Add app to settings.py
- [x] Create the model in models.py
- [x] Register the model in admin.py
- [x] Create an booking/view.py 
- [x] Update the base.html with an update to navigation if applicable
- [x] Create a template/booking/booking.html file
- [x] Create about urls.py
- [x] Add urlpattern to urls.py
