### ISSUE TITLE
Add authentication to app

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#18]
- [ ] Install and wire up AllAuth
- [ ] Add django-allauth to requirements
- [ ] Add to installed_apps
- [ ] Add constraints 
- [ ] Append to Middleware
- [ ] Update settings.py
- [ ] Add account_email_verification to auth-password_validators
- [ ] Save and migrate
- [ ] Add url pattern to urls.py
- [ ] add/modify templates
- [ ] Assign new urls to variables in base.html
- [ ] Add logout, register, and login links to navigation - these urls and views are in the allauth.account app - don’t have to create them
- [ ] Test preview
- [ ] Copy the allauth templates files to the project’s template directory 
- [ ] Update login.html and logout.html code
- [ ] Test-preview
- [ ] Deploy
- [ ] Test
- [ ]
