### ISSUE TITLE
USER STORY: Access the website pages

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#19]
As a **Site User**, I can **view/access websites public pages** so that I can **easily get general info and make a booking**

- [x] AC1 Given a user, access the site
- [x] AC2 Then each page displays information about Wimpleton House and the venue options, about, and contact information
- [x] AC3 When a user selects from the navigation bar he can access all the page info
