### ISSUE TITLE
Initial App Research

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#2]
- [x] Research venue websites
- [x] Research stock photo imagery
- [x] Research font families
- [x] Establish colour palette
- [x] Create Entity Relationship Diagrams
- [x] Design Database Models
