### ISSUE TITLE
USER STORY: Register as a Registered User

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#20]
As a **Potential Site User**, I can **register for an account** so that **I can access the booking area, make a venue booking, and see my bookings**

- [x] User can create an account with their name and email
- [x] Checks for valid name
- [ ] Checks for valid email address
