### ISSUE TITLE
USER STORY: Sign-in / Sign Out as a Registered User

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#21]
As a **Registered User**, I can **sign into or out of the site** so that **I can make/manage my booking(s)**

- [x] AC1 Can access the sign in/sign out page via the navication bar
- [x] AC2 A form with detail input appears to be completed by user
- [x] AC3 When the user fills out all the required fields and submits the form, he/she will be authorized to make/view/adjust/delete bookings
