### ISSUE TITLE
USER STORY: SuperUser admin access to admin dashboard

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#22]
As a **Super User or Admin**, I can **access the admin panel/dashboard** so that **I can edit venue information, about us, information, make/edit/review/update/delete bookings**

- [x] AC1 Super user can log into admin panel as an authorized user
- [x] AC2 Super user has access to venues and can create/edit/delete venue information
- [x] AC3 Super user has access to bookings and can create/edit/delete booking information
- [x] AC4 Super user has access to About page and can add/edit/delete About information

**Comment by hysinh** [comment]
Tasks 
- [x] Update admin file to include booking, venue, and contact models
- [x] Update filtering and display of models
