### ISSUE TITLE
USER STORY: Access and View the Venue Section as a paginated list

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#23]
As a **Site User,** I can **easily review the venue hire options available at the Wimpleton house** so that **I can make a decision about which venue option to choose**

- [x] AC1 A link on the navigation and on the home page to go to the venue page
- [x] AC2 A synopsis of all the venue options should be viewable
- [ ] AC3 A button or link should allow users to access more detail information for each
