### ISSUE TITLE
USER STORY: Manage bookings as a registered user

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#26]
As a **Registered User,** I can **view/update/delete any of my bookings** so that **manage the details of each of my bookings**

- [x] AC1 Given that I am an authorized user, I can view all of my current bookings.
- [x] AC2 Given that I am an authorized user, I can update and manage any of my current bookings by clicking on an update button for each booking.
- [x] AC3 Given that I am an authorized user, I can delete any of my current bookings.
