### ISSUE TITLE
USER STORY; Manage bookings as Site Admin

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#29]
As a **Site admin**, I can **create and manage any booking** so that **I can manage the bookings for the venue**

- [x] AC1 Given that I am the site admin with the proper credentials, I can view all of the bookings made by all the customers.
- [x] AC2 Given that I am the site admin, I can approve or cancel a booking request

**Comment by hysinh** [comment]
Tasks - Build the Booking model
- [x] Add attributes to the booking model
- [x] migrate
- [x] import model to admin.py
- [x] Test as superuser
- [x] Manual deployment to Heroku
- [x] include ordering so that booking are listed in order of Event date

Tasks - Set up the superuser
- [x] Create superuser admin account
