### ISSUE TITLE
User Story: Create Venue options as Site Admin

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#30]
As a **Site admin**, I can **add/update/delete venue options** so that **the most updated venue options are available for site users to book**

- [x] AC1 Can add/update/delete venue options

**Comment by hysinh** [comment]
- [x] Using ERD, create models in models.py
- [x] import models.py, import user
- [ ] add attributes to model
- [x] migrate
- [x] update settings.py with CSRF_TRUSTED_ORIGINA
- [x] Add model to admin.py - import Models
- [x] Test as superuser
- [x] Make deploytment to Heroku
