### ISSUE TITLE
Planning for application 

### ISSUE THREAD

**Issue by hysinh** [hysinh/wimpleton-booking-app#4]
Planning Tasks:

- [ ] Write user stories
- [ ] Design Entity Relationship Diagrams
- [ ] Design Database Models
- [ ] Research content
- [ ] Find stockphotos
- [ ] Design mockups, wireframes, and flowchart
- [ ] Establish color scheme
